# Generated by Django 4.2.6 on 2024-12-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=None, max_length=50)),
                ('email', models.CharField(blank=None, max_length=250)),
                ('senha', models.CharField(blank=None, max_length=50)),
                ('tipo', models.CharField(default=0, max_length=50)),
                ('telefone', models.IntegerField()),
                ('cidade', models.CharField(blank=None, max_length=50)),
            ],
        ),
    ]
