# Generated by Django 4.2.6 on 2024-12-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste_complemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
