# Generated by Django 5.1.4 on 2025-01-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0004_teste_ong_rename_teste_user_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teste_complemento',
            new_name='user_complemento',
        ),
    ]
