# Generated by Django 5.1.4 on 2025-01-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0005_rename_teste_complemento_user_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='test_hash',
            field=models.UUIDField(default=0, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
