# Generated by Django 5.1.4 on 2025-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0006_user_info_test_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='test_hash',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
