# Generated by Django 5.1.4 on 2025-01-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0007_alter_user_info_test_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='test_hash',
            new_name='enctype_hash',
        ),
    ]
