# Generated by Django 5.0.6 on 2025-01-27 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0009_alter_user_complemento_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('castramento', models.BooleanField(default=False)),
                ('data_pub', models.DateTimeField(default=datetime.datetime(2025, 1, 27, 4, 23, 55, 729948, tzinfo=datetime.timezone.utc), editable=None)),
            ],
        ),
    ]
