# Generated by Django 5.0.6 on 2025-01-27 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0010_pubinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubinfo',
            name='creator',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pubinfo',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 14, 1, 37, 821209, tzinfo=datetime.timezone.utc), editable=None),
        ),
    ]
