# Generated by Django 5.0.6 on 2025-01-27 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0011_pubinfo_creator_alter_pubinfo_data_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubinfo',
            name='imgpub',
            field=models.ImageField(blank=True, null=True, upload_to='pub_img/'),
        ),
        migrations.AlterField(
            model_name='pubinfo',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 14, 5, 43, 880720, tzinfo=datetime.timezone.utc), editable=None),
        ),
    ]
