# Generated by Django 5.1 on 2025-01-29 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0014_alter_pubinfo_data_pub_alter_pubinfo_imgpub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubinfo',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 17, 49, 19, 323277, tzinfo=datetime.timezone.utc), editable=None),
        ),
        migrations.AlterField(
            model_name='pubinfo',
            name='titulo',
            field=models.CharField(default='IMG_SEC', max_length=10),
        ),
    ]
