# Generated by Django 5.1 on 2025-02-03 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0015_alter_pubinfo_data_pub_alter_pubinfo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubinfo',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 17, 38, 21, 299468, tzinfo=datetime.timezone.utc), editable=None),
        ),
    ]
