# Generated by Django 5.1 on 2025-02-04 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0017_pubinfo_tipo_n_alter_pubinfo_data_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubinfo',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pubinfo',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pubinfo',
            name='raca',
            field=models.CharField(default='Desconhecida', max_length=50),
        ),
        migrations.AddField(
            model_name='pubinfo',
            name='sexo',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='pubinfo',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 18, 5, 15, 875798, tzinfo=datetime.timezone.utc), editable=None),
        ),
    ]
