# Generated by Django 5.1 on 2025-02-04 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0018_pubinfo_desc_pubinfo_idade_pubinfo_raca_pubinfo_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubinfo',
            name='castramento',
            field=models.CharField(default='Não', max_length=5),
        ),
        migrations.AlterField(
            model_name='pubinfo',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 20, 46, 45, 94947, tzinfo=datetime.timezone.utc), editable=None),
        ),
    ]
