# Generated by Django 5.0.6 on 2025-02-08 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0020_fav_user_alter_pubinfo_data_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubinfo',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 15, 20, 1, 759865, tzinfo=datetime.timezone.utc), editable=None),
        ),
    ]
