# Generated by Django 5.0.6 on 2025-02-10 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0021_alter_pubinfo_data_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoAdotar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.IntegerField()),
                ('destinatario', models.IntegerField()),
                ('pub_selec', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pubinfo',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 11, 57, 41, 892292, tzinfo=datetime.timezone.utc), editable=None),
        ),
    ]
