# Generated by Django 5.1 on 2025-02-10 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0022_requisicaoadotar_alter_pubinfo_data_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaoadotar',
            name='msg',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pubinfo',
            name='data_pub',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=None),
        ),
    ]
