# Generated by Django 5.0.6 on 2025-02-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0023_requisicaoadotar_msg_alter_pubinfo_data_pub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste_ong',
        ),
        migrations.AddField(
            model_name='requisicaoadotar',
            name='log_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisicaoadotar',
            name='resposta',
            field=models.CharField(default='Não Respondida', max_length=25),
        ),
    ]
